import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.scss";
import { ThemeProvider } from "@/context/theme-provider";
import NextTopLoader from 'nextjs-toploader';

export const vazir = localFont({
  src: [
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-Thin.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-ExtraLight.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-ExtraBold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../public/fonts/webfonts/Vazirmatn-RD-FD-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-vazirmatn-rd-fd',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={`${vazir.className}`}>
        <NextTopLoader color="#9B2E39" />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
